defmodule Animation do
  @frame_time 100
  @default_world """
  .....................o......................................
  .......................o....................................
  ...................o.o..............o...........o..o........
  .................................oo.o..o...ooo....oo........
  ..........oo.o...ooo....o.......o.o..ooo...ooo..o...........
  ...........o.o.o.oo.............................o...........
  .......................o........o....o.......o..o...........
  .............o.o................o....o.o.....o..............
  ............o.oo........o.......oo.....o..o.................
  ............o..........o.........o..o....oo.oo..............
  .......................ooo.......o.oo.......................
  ...........oooooo......oooo......ooo......o.................
  ...........oooooo......oooo.....o...o.......................
  ...........oooooo......o..o.....o...o.......................
  ......o.o.....o.o.o.o.ooo.o.....o.o.......o.................
  ....o....o...o.o.o..o.......................................
  ....o.oo.o.o..o.o.ooo...............oo.o..o.................
  ......o.o.o.................................................
  ............................................................
  """

  def play(iterations)do
    play(@default_world, iterations)
  end

  def play(world, iterations) do
    next_iteration(world, iterations)
  end

  defp next_iteration(world, i) when i > 0 do
    IO.write(IO.ANSI.clear())
    IO.write(IO.ANSI.home())

    GameOfLife.draw(world)

    Process.sleep(@frame_time)

    next_iteration(GameOfLife.next(world), i - 1)
  end

  defp next_iteration(_, i) when i == 0 do
  end
end
